<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AlertRule extends Model
{
    use HasFactory;

    protected $fillable = [
        'code',
        'severity',
        'condition',
        'cooldown_hours',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'condition' => 'array',
            'is_active' => 'boolean',
        ];
    }

    /**
     * Get the alerts generated by this rule.
     */
    public function alerts(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Alert::class, 'rule_code', 'code');
    }
}
